---
data_root: 'C:\Study\Soft-DTW-AWE\speech_dataset'
model_root: 'C:\Study\Soft-DTW-AWE\models'
report_root: 'C:\Study\Soft-DTW-AWE\reports'


wanted_words:
#  - 'bed'
#  - 'bird'
#  - 'cat'
#  - 'dog'
#  - 'down'
#  - 'eight'
#  - 'five'
#  - 'four'
#  - 'go'
#  - 'happy'
#  - 'house'
#  - 'left'
  - 'marvin'
  - 'nine'
  - 'no'
  - 'off'
  - 'on'
  - 'one'
  - 'right'
  - 'seven'
  - 'sheila'
  - 'six'
  - 'stop'
  - 'three'
  - 'tree'
  - 'two'
  - 'up'
  - 'wow'
  - 'yes'
  - 'zero'


dct_coefficient_count: 13
mfcc_num: 39
batch_norm: True
hidden_fc:
- 256
- 256
hidden_reccurent:
- 256
- 256
winlen: 0.02
winstep: 0.01
open_end: False
dist: 'l1'
margin: 0.4
dropout: 0.3
bidirectional: False



loss_type: 'sdtw' # cos_hinge, sdtw, l2, ce
alpha: 0.0

triplet_anneal_k: 0.0025
triplet_anneal_b: 2500

train_steps: 50000
mini_batch_size: 64

learning_rate: 0.001


